# Generated by Django 6.0.3 on 2026-04-01 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tag', models.CharField(blank=True, choices=[('POWER_DISTRIBUTION', 'Power Distribution'), ('LIGHTING', 'Lighting'), ('WATER_SUPPLY', 'Water Supply'), ('DRAINAGE', 'Drainage'), ('VENTILATION', 'Ventilation'), ('HEATING', 'Heating'), ('COOLING', 'Cooling'), ('AIR_QUALITY', 'Air Quality'), ('FIRE_SUPPRESSION', 'Fire Suppression'), ('FIRE_DETECTION', 'Fire Detection'), ('SECURITY_MONITORING', 'Security Monitoring'), ('ACCESS_CONTROL', 'Access Control'), ('EMERGENCY_LIGHTING', 'Emergency Lighting'), ('PRODUCTION_EQUIPMENT', 'Production Equipment'), ('WORKSHOP_TOOL', 'Workshop Tool'), ('TRANSPORT_EQUIPMENT', 'Transport Equipment'), ('STORAGE_EQUIPMENT', 'Storage Equipment'), ('NETWORK_INFRASTRUCTURE', 'Network Infrastructure'), ('SERVER_EQUIPMENT', 'Server Equipment'), ('COMMUNICATION_SYSTEM', 'Communication System'), ('CLEANING_EQUIPMENT', 'Cleaning Equipment'), ('WASTE_MANAGEMENT', 'Waste Management'), ('KITCHEN_APPLIANCE', 'Kitchen Appliance')], max_length=50, null=True)),
                ('status', models.CharField(choices=[('101', 'Operational'), ('301', 'Out of order'), ('501', 'Maintenance'), ('502', 'For repair'), ('202', 'Awaiting maintenance'), ('201', 'Awaiting repair')], default='101', max_length=50)),
                ('serial_number', models.CharField(blank=True, max_length=255)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('model_number', models.CharField(blank=True, max_length=255)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('warranty_expiration', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='facilities.room')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.assetcategory')),
            ],
            options={
                'ordering': ['category__name', 'name'],
            },
        ),
    ]
