# Generated by Django 6.0.3 on 2026-04-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='asset',
            name='category',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='tag',
        ),
        migrations.AddField(
            model_name='asset',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='assets', to='assets.assetcategory'),
        ),
    ]
