# Generated by Django 6.0.3 on 2026-04-06 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='work_orders',
            field=models.ManyToManyField(related_name='spare_parts', through='inventory.StockMovement', to='maintenance.workorder'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.sparepart'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='maintenance.workorder'),
        ),
    ]
